# Generated by Django 5.1.6 on 2025-02-13 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkGraphSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('graph_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='NetworkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_nodes', models.IntegerField()),
                ('active_nodes', models.IntegerField()),
                ('total_packets', models.IntegerField()),
                ('avg_latency', models.FloatField()),
                ('avg_energy', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NeuronMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('neuron_id', models.IntegerField()),
                ('energy_level', models.FloatField()),
                ('congestion_level', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RoutingPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stdp_path', models.TextField()),
                ('stdp_path_score', models.FloatField(blank=True, null=True)),
                ('source_node', models.IntegerField()),
                ('destination_node', models.IntegerField()),
                ('neighbor_scores_history_json', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SNNSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_rate', models.FloatField(default=0.01)),
                ('synaptic_weight', models.FloatField(default=0.005)),
                ('firing_threshold', models.FloatField(default=-54)),
                ('reset_potential', models.FloatField(default=-65)),
                ('tau_pre', models.FloatField(default=20)),
                ('tau_post', models.FloatField(default=20)),
                ('simulation_time', models.FloatField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PathHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path_type', models.CharField(choices=[('DIJKSTRA', 'Dijkstra'), ('STDP', 'STDP-guided')], max_length=10)),
                ('path_nodes', models.JSONField()),
                ('source_node', models.IntegerField()),
                ('destination_node', models.IntegerField()),
                ('routing_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path_history_entries', to='main_project.routingpath')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('simulation_time_ms', models.FloatField()),
                ('firing_rates_json', models.TextField()),
                ('latencies_ms_json', models.TextField()),
                ('energy_levels_json', models.TextField()),
                ('congestion_levels_json', models.TextField()),
                ('routing_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_data_points', to='main_project.routingpath')),
            ],
            options={
                'verbose_name': 'Simulation Data Point',
                'verbose_name_plural': 'Simulation Data Points',
            },
        ),
    ]
