# Generated by Django 5.1.7 on 2025-03-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkstatus',
            name='avg_congestion',
            field=models.FloatField(default=0.0),
        ),
    ]
